### PR TITLE
Add defaul internal http interface and port for container usage

### PR DESCRIPTION
**Pull request by banh-gao**
I've set some defaults internal server network interface and port with the needed values to use the service in docker.
I've also add the expose command so that docker daemon will know on which port of the container to expose (useful for reverse proxies).

### CODE REVIEW

**Comment by horazont** [comment]
Hi! Thanks for your PR.

Could you also remove the defaulting in https://github.com/snikket-im/snikket-web-portal/blob/master/docker/entrypoint.sh please?

**Comment by horazont** [comment]
@banh-gao Thanks.

I just realized that you changed the default from 127.0.0.1 to 0.0.0.0.

The default of 127.0.0.1 was set to avoid exposing the web portal in `--net host` situations (which is the default in https://github.com/snikket-im/snikket-selfhosted/).

I am hesitant to change this because of the problems which could arise from accidentally exposing the web portal over HTTP instead of HTTPS, so could you please:

- Change the default back to 127.0.0.1
- Squash your commits together

Thanks!

**Comment by banh-gao** [comment]
What is the reason for exposing the whole container on the host network?
Would not be more secure to just expose the snikket proxy and connect it to other containers through an internal docker network defined in the docker compose itself?

This is the approach I've followed on my installation where I'm using a traefik as reverse proxy and TLS termination.

**Comment by horazont** [comment]
@banh-gao The TURN server and docker’s userspace proxying really did not go well together (waaaaay too many ports).

That meant that at least snikket-server had to run in host mode. That makes linking the containers in docker compose by hostname impossible, hence the web portal also runs in host mode so that it can connect to prosody via 127.0.0.1.

In addition, not relying on docker networking makes support for IPv6 more realistic.

**Comment by banh-gao** [comment]
I see this can be tricky if you have many ports to expose and it could be reasonable to use this kind of networking setup for this particular use case.

However I think the configuration of the listening interface to localhost should be in the same place where the container net is set in host mode (i.e. the docker compose). This is because running containers on host network increases the attack surface but at the same time it is reduced by setting the interface to only listen on localhost.
Moving the interface configuration to the docker compose also allows to run the portal container out of the box without the need of special configurations (which was the original issue I faced while trying to start the portal).

**Comment by horazont** [comment]
@banh-gao I created https://github.com/snikket-im/snikket-selfhosted/pull/5 to address that. Once that is merged, we can proceed here.

**Comment by horazont** [comment]
@banh-gao See the note over here: https://github.com/snikket-im/snikket-selfhosted/pull/5#issuecomment-1019279708

**Pull request closed without merging**
